[firebase]
type = "service_account"
project_id = "billing-system-aae2b"
private_key_id = "2484d28548bc6d576739d98400c1b85ce44eec02"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDZqIYFuRepgJ4+
yUJ4Re1wrduTc7Fp8vGawpZyZgBCGHRoCJpSDnvtyEnOoYW1sFHPIKD1ANvh8Zgg
WgaV0y4eVMtSKeFTJkl0exij7CXX+qMnZ9ALgkHcNmw1mdI2qApMWNio0n0h7o1W
uNGeX/yEAidpE1x4YqfWF967J8Jw6tSojT23hhDZO2ODt1PwTIfw36rOFHA080SB
ejVHRqJBOYots41Ltzd+mKuxLRWykjenSzSKYAfcsSOQG9+3F23Ky6hj0zW4WtLo
U/jCfsFc0jadBn/eagO9nc5W+aCtDyCsaIp/ZBRGFYQIgrqA8wzV1bq2y9KkPSxb
hDkjB5mxAgMBAAECggEAZBpSkT1AOa+yl9O+I0yd2C3Nh7I0zTJzlaaaxMBOrBdN
Ki+SsdyBeKmd8E9vDFGsPmOWQzgC6JZRTce5sZxvYHnFDOPAAprgO5cFjRZljUBz
WwMutqxQl/PbrocxG/wKyHQwKOytqjZpgJH9riYdH6VR9Mx3wdI1uIw/3rl5fq5Y
WmRld0DUIxnTsTzf0TG4BblpG1fBc21tFj9J+MLqL8HIRh/cvAZo028gTNTgttQN
/8ADzNZvWhBTvr0GIDfNuIzKy4JFKaginzt+OSE5ksygN/jVtisnKxUjSEy1ZJSA
nMURiGYUycu+nzBo/RkahWm0luUfRDcYxbfQsisI1QKBgQD61hWETis5n54V96RQ
qnyW0jYJXnYhgE+NS7wP5tOW8fTRWouzfanwiQFJ9FqsCT/7DpCJhlKMVgcv/aGB
wKO9ONszAIRwWT/nKOY6lC84Sscz4D0bZL3+EUTsGehz3IfyLw05hm3JAMqOb8wd
y4qW1WDX3+CVtilO5+ZcL9cfjwKBgQDeI5ckggrubf5gO2yrNmAMPEiyW2Nj8AbJ
dw3NytA50oajm+v9i899Jg4fOdxHBxuD3dKux5g0L4QDU7AqXPfQVRrn3A7aMq6c
SevblG6DcGuOIFQ8rNQ1y3+aJInGkYH/vVceNBIvT7fbvj7WJTBoW2KZiUh12ZjN
16FO0kESvwKBgQCS2YL/UkQ8GBaVBcZM84K9SZQZKBRAyL3KGuye4qQ9WqnZZwki
rA8xowP+J/Bth3zNnllAKkNppXPPxM0pCX7S6NZrpYHjxFyFGIyw/tAmRKEa3czo
nLIebD3Ne91690EfqCw14V2kr7Hmcc0uJFueso1f1NHG1D6a02kpz1hCQQKBgQDX
onDbrajy3q9ptwW8BeKivfpLuM74ek38T6eEt3X+S1ELjRY+X/OgpspaoY4lHM8m
6LPVmkczkVRy7lA6L1kYUST3IfUA9uXtLQzZcHL/AKhHpTZgV90AA3TwqrtbmHA7
Uw84cI+egaIWm8zfj+Y3x04lgNBoJjxgxQr/OraUfQKBgQDkf3OjlHhi/fa6KbDY
Pcg3c4A/w6UEFTmQcY3P/v5MBhF+mm7N1lkMCwMSDL8GV/3epCTRRclPCAROTTPP
v1wvwekeu7vObLfMU1Z0F4mgjogb41DYRVvFV1UddpkDC5NPsUw4wJ2Gc6gWoGsX
QHK49rl+Px58kI0tfku5lNKp0g==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@billing-system-aae2b.iam.gserviceaccount.com"
client_id = "112802302047798811723"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40billing-system-aae2b.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
database_url = "https://billing-system-aae2b-default-rtdb.firebaseio.com/"
